"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppSignature from "@/components/AppSignature";
import { communityRecipes, loadLocalCommunityRecipes, saveLocalCommunityRecipes, type CommunityStyle, type LocalCommunityRecipe } from "@/lib/community-recipes";
import { flourById } from "@/lib/flours";
import { recipeParams, settingsFromUrl } from "@/lib/recipe-url";
import type { RecipeSettings } from "@/lib/saved-recipes";

type OvenFilter = "all" | "gas" | "home";
const defaults: RecipeSettings = { pizzas: 6, ballWeight: 260, waste: 3, hydration: 64, salt: 2.8, yeastType: "idy", fermentation: "24h-cold", temperature: 4, goal: "balanced", ovenType: "gas", flourId: "caputo-pizzeria" };
const copy = {
  fi: { back: "Laskuri", eyebrow: "Community Recipes", title: "Hyvät reseptit paranevat, kun niitä jaetaan.", intro: "Tutki pizzayhteisöistä tuttuja lähtöasetelmia, suodata omaan uuniisi sopivat ja siirrä resepti laskuriin yhdellä painalluksella.", all: "Kaikki", gas: "Kaasu-uuni", home: "Sähköuuni", use: "Käytä reseptiä", share: "Jaa", copied: "Linkki kopioitu", difficulty: "Vaikeus", styles: { neapolitan: "Napolilainen", airy: "Ilmava", home: "Sähköuuni", crisp: "Rapea", pan: "Pannupizza" }, current: "Jaa oma reseptisi", currentIntro: "Nykyiset laskurin asetukset liitetään korttiin. Tallenna kortti omalle laitteelle ja jaa reseptilinkki puhelimen jakovalikosta.", titleLabel: "Reseptin nimi", titlePlaceholder: "Marcin viikonloppupizza", creator: "Tekijän nimi", creatorPlaceholder: "Mara", note: "Lyhyt vinkki tai tarina", notePlaceholder: "Toimii parhaiten, kun pallot lämpenevät kolme tuntia…", save: "Tallenna jaettavaksi", mine: "Omat yhteisöreseptit", empty: "Et ole vielä tallentanut omaa jaettavaa reseptiä.", local: "Tallennukset ovat tällä laitteella. Jakolinkki toimii muille ilman käyttäjätiliä.", delete: "Poista", saved: "Resepti tallennettu", curated: "Yhteisöjen lähtöreseptit", noFake: "Reseptit ovat läpinäkyviä lähtöasetelmia – eivät keksittyjä käyttäjäarvioita tai tykkäysmääriä." },
  en: { back: "Calculator", eyebrow: "Community Recipes", title: "Good recipes improve when people share them.", intro: "Explore useful baselines familiar from pizza communities, filter for your oven and apply one to the calculator in a tap.", all: "All", gas: "Gas oven", home: "Electric oven", use: "Use recipe", share: "Share", copied: "Link copied", difficulty: "Difficulty", styles: { neapolitan: "Neapolitan", airy: "Airy", home: "Electric oven", crisp: "Crisp", pan: "Pan pizza" }, current: "Share your recipe", currentIntro: "The current calculator settings are attached to the card. Save it on this device and share the recipe link using your phone.", titleLabel: "Recipe name", titlePlaceholder: "My weekend pizza", creator: "Creator name", creatorPlaceholder: "Mara", note: "Short tip or story", notePlaceholder: "Best when the dough balls warm for three hours…", save: "Save for sharing", mine: "My community recipes", empty: "You have not saved a shareable recipe yet.", local: "Entries stay on this device. The shared link works for others without an account.", delete: "Delete", saved: "Recipe saved", curated: "Community starter recipes", noFake: "These are transparent starting setups – not invented user reviews or like counts." },
} as const;

export default function CommunityPage() {
  const [ready, setReady] = useState(false); const [settings, setSettings] = useState(defaults); const [oven, setOven] = useState<OvenFilter>("all"); const [style, setStyle] = useState<CommunityStyle | "all">("all"); const [mine, setMine] = useState<LocalCommunityRecipe[]>([]); const [title, setTitle] = useState(""); const [creator, setCreator] = useState(""); const [note, setNote] = useState(""); const [notice, setNotice] = useState(""); const t = copy.en;
  useEffect(() => { const shared = settingsFromUrl(location.search); setSettings({ ...defaults, ...Object.fromEntries(Object.entries(shared).filter(([, value]) => value !== undefined)) }); setMine(loadLocalCommunityRecipes()); document.documentElement.lang = "en"; setReady(true); }, []);
  const filtered = useMemo(() => communityRecipes.filter(recipe => (oven === "all" || recipe.settings.ovenType === oven) && (style === "all" || recipe.style === style)), [oven, style]);
  if (!ready) return <main className="min-h-screen bg-cream"/>;
  const shareRecipe = async (recipeSettings: RecipeSettings, name: string) => { const url = `${location.origin}/?${recipeParams(recipeSettings)}`; const shareData = { title: name, text: `Try this DoughTools recipe: ${name}`, url }; try { if (navigator.share) await navigator.share(shareData); else { await navigator.clipboard.writeText(`${shareData.text}\n${url}`); setNotice(t.copied); } } catch { /* User cancelled the share sheet. */ } };
  const saveMine = () => { if (!title.trim()) return; const entry: LocalCommunityRecipe = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), title: title.trim(), creator: creator.trim() || "—", note: note.trim(), settings }; const next = [entry, ...mine]; setMine(next); saveLocalCommunityRecipes(next); setTitle(""); setNote(""); setNotice(t.saved); };
  const removeMine = (id: string) => { const next = mine.filter(item => item.id !== id); setMine(next); saveLocalCommunityRecipes(next); };
  return <main className="min-h-screen bg-cream px-4 py-5 text-ink sm:px-6 sm:py-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-tomato text-white">♥</span><strong>Dough<span className="text-tomato">Tools</span></strong></Link><Link href={`/?${recipeParams(settings)}`} className="rounded-full bg-ink px-4 py-2 text-xs font-bold text-white">{t.back}</Link></header>
    <section className="py-10 sm:py-14"><p className="text-xs font-extrabold uppercase tracking-[.22em] text-tomato">{t.eyebrow}</p><h1 className="mt-3 max-w-4xl font-display text-4xl font-semibold leading-none sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-ink/55 sm:text-base">{t.intro}</p></section>
    <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-3xl font-semibold">{t.curated}</h2><p className="mt-2 text-xs text-ink/45">{t.noFake}</p></div><div className="flex gap-2 overflow-x-auto pb-1">{(["all", "gas", "home"] as OvenFilter[]).map(key => <button type="button" key={key} onClick={() => setOven(key)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${oven === key ? "bg-ink text-white" : "border border-ink/10 bg-white"}`}>{t[key]}</button>)}</div></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2"><button type="button" onClick={() => setStyle("all")} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${style === "all" ? "bg-tomato text-white" : "bg-tomato/10 text-tomato"}`}>{t.all}</button>{(Object.keys(t.styles) as CommunityStyle[]).map(key => <button type="button" key={key} onClick={() => setStyle(key)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${style === key ? "bg-tomato text-white" : "bg-tomato/10 text-tomato"}`}>{t.styles[key]}</button>)}</div>
      <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(recipe => { const name = recipe.nameEn; const flour = flourById(recipe.settings.flourId); return <article key={recipe.id} className="overflow-hidden rounded-[1.5rem] border border-white bg-white/80 shadow-card"><div className="relative aspect-[16/10]"><Image src={recipe.image} alt={name} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover"/><span className="absolute left-3 top-3 rounded-full bg-ink/85 px-3 py-1.5 text-[10px] font-bold text-white">{t.styles[recipe.style]}</span></div><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-leaf">{recipe.sourceEn}</p><h3 className="mt-2 font-display text-2xl font-semibold">{name}</h3><p className="mt-2 min-h-12 text-xs leading-5 text-ink/50">{recipe.descriptionEn}</p><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-ink/[.04] p-3 text-xs"><span>{recipe.settings.ballWeight} g · {recipe.settings.hydration} %</span><span className="text-right">{"●".repeat(recipe.difficulty)}{"○".repeat(3 - recipe.difficulty)}</span><span className="truncate text-ink/45">{flour.brand} {flour.name}</span><span className="text-right text-ink/45">{recipe.settings.fermentation.replaceAll("-", " ")}</span></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><Link href={`/?${recipeParams(recipe.settings)}`} className="rounded-xl bg-tomato px-4 py-3 text-center text-xs font-extrabold text-white">{t.use} →</Link><button type="button" onClick={() => shareRecipe(recipe.settings, name)} className="rounded-xl border border-ink/10 bg-white px-4 text-xs font-bold">{t.share}</button></div></div></article>})}</div></section>
    <section className="mt-14 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-[1.5rem] bg-ink p-6 text-white"><p className="text-xs font-extrabold uppercase tracking-wider text-oven-gold">{t.current}</p><h2 className="mt-3 font-display text-3xl font-semibold">{settings.pizzas} × {settings.ballWeight} g · {settings.hydration} %</h2><p className="mt-2 text-xs text-white/45">{flourById(settings.flourId).brand} {flourById(settings.flourId).name} · {settings.fermentation.replaceAll("-", " ")}</p><div className="mt-6 space-y-3"><label className="block text-xs font-bold text-white/60">{t.titleLabel}<input value={title} onChange={e => setTitle(e.target.value)} placeholder={t.titlePlaceholder} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/10 px-3 text-sm text-white outline-none placeholder:text-white/25"/></label><label className="block text-xs font-bold text-white/60">{t.creator}<input value={creator} onChange={e => setCreator(e.target.value)} placeholder={t.creatorPlaceholder} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/10 px-3 text-sm text-white outline-none placeholder:text-white/25"/></label><label className="block text-xs font-bold text-white/60">{t.note}<textarea value={note} onChange={e => setNote(e.target.value)} placeholder={t.notePlaceholder} rows={3} className="mt-2 w-full rounded-xl border border-white/10 bg-white/10 p-3 text-sm text-white outline-none placeholder:text-white/25"/></label><button type="button" disabled={!title.trim()} onClick={saveMine} className="w-full rounded-xl bg-tomato px-4 py-3 text-sm font-extrabold disabled:opacity-40">{t.save}</button>{notice && <p className="text-center text-xs text-oven-gold">{notice}</p>}</div></article>
      <article className="rounded-[1.5rem] bg-white/80 p-6 shadow-card"><h2 className="font-display text-3xl font-semibold">{t.mine}</h2><p className="mt-2 text-xs text-ink/45">{t.local}</p><div className="mt-5 space-y-3">{mine.length === 0 ? <p className="rounded-xl bg-ink/[.04] p-5 text-sm text-ink/45">{t.empty}</p> : mine.map(recipe => <div key={recipe.id} className="rounded-xl border border-ink/10 p-4"><div className="flex items-start justify-between gap-3"><div><strong>{recipe.title}</strong><p className="mt-1 text-xs text-ink/40">{recipe.creator} · {recipe.settings.pizzas} × {recipe.settings.ballWeight} g · {recipe.settings.hydration} %</p>{recipe.note && <p className="mt-2 text-xs leading-5 text-ink/55">{recipe.note}</p>}</div><button type="button" onClick={() => removeMine(recipe.id)} className="text-xs font-bold text-tomato">{t.delete}</button></div><div className="mt-3 flex gap-2"><Link href={`/?${recipeParams(recipe.settings)}`} className="rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white">{t.use}</Link><button type="button" onClick={() => shareRecipe(recipe.settings, recipe.title)} className="rounded-lg border border-ink/10 px-3 py-2 text-xs font-bold">{t.share}</button></div></div>)}</div></article></section>
    <footer className="mt-10 border-t border-ink/10 py-6"><AppSignature /></footer>
  </div></main>;
}
