import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Camera,
  Calendar,
  ChefHat,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  CircleDot,
  CircleUserRound,
  CircleX,
  Clock,
  CookingPot,
  Download,
  ExternalLink,
  Flame,
  History,
  Info,
  ListChecks,
  Menu,
  Minus,
  PackageOpen,
  PartyPopper,
  Pencil,
  Pizza,
  Plus,
  Refrigerator,
  RotateCcw,
  Scale,
  Share2,
  ShoppingBasket,
  Soup,
  Sparkles,
  Thermometer,
  Timer,
  Trash2,
  TriangleAlert,
  Waves,
  Wheat,
  X,
  type LucideIcon,
} from "lucide-react";

export const doughToolsIconMap = {
  account: CircleUserRound,
  add: Plus,
  archive: Archive,
  back: ArrowLeft,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "chef-hat": ChefHat,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  checklist: ListChecks,
  clock: Clock,
  close: X,
  delete: Trash2,
  download: Download,
  edit: Pencil,
  error: CircleX,
  "experience-level": Sparkles,
  "external-link": ExternalLink,
  flame: Flame,
  forward: ArrowRight,
  history: History,
  information: Info,
  "kitchen-mode": ChefHat,
  menu: Menu,
  "mixing-bowl": Soup,
  oven: CookingPot,
  party: PartyPopper,
  pizza: Pizza,
  refrigerator: Refrigerator,
  remove: Minus,
  restore: RotateCcw,
  salt: CircleDot,
  scale: Scale,
  share: Share2,
  "shopping-basket": ShoppingBasket,
  success: CircleCheck,
  thermometer: Thermometer,
  timeline: ListChecks,
  timer: Timer,
  warning: TriangleAlert,
  water: Waves,
  wheat: Wheat,
  yeast: PackageOpen,
} as const satisfies Record<string, LucideIcon>;

export type DoughToolsIconName = keyof typeof doughToolsIconMap;

export const doughToolsIconNames = Object.keys(doughToolsIconMap) as DoughToolsIconName[];
