"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import SiteFooter from "@/components/SiteFooter";
import { flourById } from "@/lib/flours";
import { buildCoachAdvice, type CoachGoal, type CoachIssue } from "@/lib/pizza-coach";
import { recipeParams, settingsFromUrl } from "@/lib/recipe-url";
import type { RecipeSettings } from "@/lib/saved-recipes";

type Locale = "fi" | "en";
const defaults: RecipeSettings = { pizzas: 6, ballWeight: 260, waste: 3, hydration: 64, salt: 2.8, yeastType: "idy", fermentation: "24h-cold", temperature: 4, goal: "balanced", ovenType: "gas", flourId: "caputo-pizzeria" };
const copy = {
  fi: { back: "Laskuri", journal: "Päiväkirja", eyebrow: "Pizza Coach", title: "Kerro tavoite. Valmentaja lukee reseptisi.", intro: "Saat reseptiin, jauhoon ja uuniin perustuvan toimintasuunnitelman. Kaikki analyysi tapahtuu tällä laitteella.", goal: "Mitä haluat parantaa?", issue: "Mitä viimeksi tapahtui?", analyse: "Valmentajan analyysi", current: "Nykyinen resepti", apply: "Käytä ehdotettuja asetuksia", noChange: "Reseptin numeroita ei tarvitse muuttaa – keskity työvaiheisiin.", warnings: "Tarkista nämä", privacy: "Paikallinen valmentaja · reseptiä tai vastauksia ei lähetetä palvelimelle", goals: { airy: ["Ilmavampi reuna", "Suuri ja kevyt rakenne"], crispy: ["Rapeampi pohja", "Vähemmän kosteutta"], easy: ["Helpompi taikina", "Ennustettava käsittely"], flavor: ["Enemmän makua", "Fermentaation syvyys"] }, issues: { none: "Ei selvää ongelmaa", sticky: "Liian tahmea", dense: "Tiivis reuna", tears: "Taikina repeilee", pale: "Pizza jää vaaleaksi", soggy: "Keskusta on vetinen", burnt: "Pohja tai reuna palaa" }, priorities: { now: "Tee nyt", next: "Muuta reseptissä", watch: "Tarkkaile" } },
  en: { back: "Calculator", journal: "Journal", eyebrow: "Pizza Coach", title: "Choose a goal. The coach reads your recipe.", intro: "Get an action plan based on your recipe, flour and oven. All analysis happens on this device.", goal: "What do you want to improve?", issue: "What happened last time?", analyse: "Coach analysis", current: "Current recipe", apply: "Apply suggested settings", noChange: "The recipe numbers do not need changing – focus on the process.", warnings: "Check these", privacy: "Local coach · your recipe and answers are not sent to a server", goals: { airy: ["Airier rim", "Large light structure"], crispy: ["Crisper base", "Less moisture"], easy: ["Easier dough", "Predictable handling"], flavor: ["More flavour", "Deeper fermentation"] }, issues: { none: "No clear problem", sticky: "Too sticky", dense: "Dense rim", tears: "Dough tears", pale: "Pizza stays pale", soggy: "Soggy centre", burnt: "Base or rim burns" }, priorities: { now: "Do now", next: "Change recipe", watch: "Watch" } },
} as const;

export default function CoachPage() {
  const locale: Locale = "en"; const [settings, setSettings] = useState(defaults); const [goal, setGoal] = useState<CoachGoal>("airy"); const [issue, setIssue] = useState<CoachIssue>("none"); const [ready, setReady] = useState(false); const t = copy.en;
  useEffect(() => { const shared = settingsFromUrl(location.search); setSettings({ ...defaults, ...Object.fromEntries(Object.entries(shared).filter(([, value]) => value !== undefined)) }); document.documentElement.lang = "en"; setReady(true); }, []);
  const flour = flourById(settings.flourId); const advice = useMemo(() => buildCoachAdvice(locale, settings, flour, goal, issue), [locale, settings, flour, goal, issue]); const originalQuery = recipeParams(settings).toString(); const recommendationQuery = recipeParams(advice.recommended).toString(); const changed = originalQuery !== recommendationQuery;
  if (!ready) return <main className="min-h-screen bg-cream"/>;
  return <main className="min-h-screen bg-cream px-4 py-5 text-ink sm:px-6 sm:py-8"><div className="mx-auto max-w-6xl">
    <header className="flex items-center justify-between"><Link href={`/?${originalQuery}`} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-tomato text-xl text-white">✦</span><strong>Dough<span className="text-tomato">Tools</span></strong></Link><div className="flex gap-2"><Link href={`/journal?${originalQuery}`} className="hidden rounded-full border border-ink/10 bg-white px-4 py-2 text-xs font-bold sm:block">{t.journal}</Link><Link href={`/?${originalQuery}`} className="rounded-full bg-ink px-4 py-2 text-xs font-bold text-white">{t.back}</Link></div></header>
    <section className="py-10 sm:py-14"><p className="text-xs font-extrabold uppercase tracking-[.22em] text-tomato">{t.eyebrow}</p><h1 className="mt-3 max-w-4xl font-display text-4xl font-semibold leading-none sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-ink/55 sm:text-base">{t.intro}</p><span className="mt-4 inline-flex rounded-full bg-leaf/[.09] px-3 py-2 text-[10px] font-bold text-leaf">🔒 {t.privacy}</span></section>
    <div className="grid items-start gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className="space-y-5 lg:sticky lg:top-5"><div className="rounded-[1.5rem] bg-white/80 p-5 shadow-card"><h2 className="text-sm font-extrabold">1. {t.goal}</h2><div className="mt-4 grid grid-cols-2 gap-2">{(Object.keys(t.goals) as CoachGoal[]).map(key => <button type="button" key={key} onClick={() => setGoal(key)} className={`rounded-xl border p-4 text-left transition ${goal === key ? "border-tomato bg-tomato text-white" : "border-ink/10 bg-white"}`}><strong className="block text-sm">{t.goals[key][0]}</strong><span className={`mt-1 block text-[10px] ${goal === key ? "text-white/65" : "text-ink/40"}`}>{t.goals[key][1]}</span></button>)}</div></div>
      <div className="rounded-[1.5rem] bg-white/80 p-5 shadow-card"><h2 className="text-sm font-extrabold">2. {t.issue}</h2><div className="mt-4 flex flex-wrap gap-2">{(Object.keys(t.issues) as CoachIssue[]).map(key => <button type="button" key={key} onClick={() => setIssue(key)} className={`rounded-full border px-4 py-2.5 text-xs font-bold transition ${issue === key ? "border-ink bg-ink text-white" : "border-ink/10 bg-white text-ink/55"}`}>{t.issues[key]}</button>)}</div></div>
      <div className="rounded-[1.5rem] bg-leaf/[.09] p-5"><p className="text-[10px] font-extrabold uppercase tracking-wider text-leaf">{t.current}</p><p className="mt-2 text-sm font-bold">{settings.pizzas} × {settings.ballWeight} g · {settings.hydration} %</p><p className="mt-1 text-xs text-ink/50">{flour.brand} {flour.name} · {settings.fermentation.replaceAll("-", " ")} · {settings.ovenType === "gas" ? "Gas" : "Home"}</p></div></section>
      <section className="overflow-hidden rounded-[1.75rem] bg-ink text-white shadow-card"><div className="border-b border-white/10 p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-tomato text-xl">✦</span><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-oven-gold">{t.analyse}</p><p className="mt-1 text-sm text-white/55">{advice.summary}</p></div></div></div>
        <div className="space-y-3 p-5 sm:p-8">{advice.actions.map((action, index) => <article key={`${action.title}-${index}`} className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><div className="flex items-start gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-white/10 text-xs font-black">{index + 1}</span><div><span className={`text-[9px] font-extrabold uppercase tracking-wider ${action.priority === "now" ? "text-oven-gold" : action.priority === "next" ? "text-[#80b4c3]" : "text-white/40"}`}>{t.priorities[action.priority]}</span><h3 className="mt-1 text-lg font-extrabold">{action.title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{action.body}</p></div></div></article>)}</div>
        {advice.warnings.length > 0 && <div className="border-t border-white/10 bg-tomato/10 p-6 sm:px-8"><strong className="text-xs text-oven-gold">{t.warnings}</strong><ul className="mt-2 space-y-2 text-xs leading-5 text-white/55">{advice.warnings.map(warning => <li key={warning}>• {warning}</li>)}</ul></div>}
        <div className="border-t border-white/10 p-5 sm:p-8">{changed ? <Link href={`/?${recommendationQuery}`} className="block rounded-xl bg-tomato px-5 py-4 text-center text-sm font-extrabold text-white">{t.apply} →</Link> : <p className="rounded-xl bg-white/[.06] p-4 text-center text-xs text-white/50">{t.noChange}</p>}</div>
      </section></div>
        <SiteFooter />
  </div></main>;
}
