import type { InstructionLocale } from "@/lib/dough-instructions";
import { getDoughStepPrimaryImageForBeginnerStep } from "@/lib/dough-step-images";

export type BeginnerStepHelp = {
  image: string;
  imageAlt: string;
  action: string[];
  why: string;
  ready: string;
  mistake: string;
};

const imageByStep: Record<string, string> = {
  prepare: getDoughStepPrimaryImageForBeginnerStep("prepare")?.src ?? "/dough-guide/guide-step-01-prepare.webp",
  mix: getDoughStepPrimaryImageForBeginnerStep("mix")?.src ?? "/dough-guide/guide-step-03-mix.webp",
  rest: getDoughStepPrimaryImageForBeginnerStep("rest")?.src ?? "/dough-guide/guide-step-04-rest.webp",
  knead: getDoughStepPrimaryImageForBeginnerStep("knead")?.src ?? "/dough-guide/guide-step-05-develop.webp",
  bulk: getDoughStepPrimaryImageForBeginnerStep("bulk")?.src ?? "/dough-guide/guide-step-06-bulk.webp",
  ball: getDoughStepPrimaryImageForBeginnerStep("ball")?.src ?? "/dough-guide/guide-step-08-ball.webp",
  cold: getDoughStepPrimaryImageForBeginnerStep("cold")?.src ?? "/dough-guide/guide-step-09-proof.webp",
  warm: getDoughStepPrimaryImageForBeginnerStep("warm")?.src ?? "/dough-guide/guide-step-10-warm.webp",
  final: getDoughStepPrimaryImageForBeginnerStep("final")?.src ?? "/dough-guide/guide-step-11-readiness.webp",
  bake: "/dough-guide/09-open.webp",
};

const fi: Record<string, Omit<BeginnerStepHelp, "image">> = {
  prepare: { imageAlt: "Jauhot, vesi, suola ja hiiva punnitaan erikseen", action: ["Aseta tyhjä astia vaa'alle ja nollaa vaaka jokaisen aineksen välissä.", "Punnitse jauhot ja vesi grammoina. Mittaa suola erikseen.", "Mittaa alle gramman hiiva 0,01 g tarkkuusvaa'alla."], why: "Taikina reagoi jo muutaman gramman eroon. Punnitseminen tekee lopputuloksesta toistettavan, kun taas desimitat eivät ole riittävän tarkkoja.", ready: "Kaikki neljä ainesta ovat erillisissä astioissa ja vaa'an lukema on tarkistettu.", mistake: "Älä kaada hiivaa suoraan pussista taikinaan – liian suuri määrä voi pilata pitkän kohotuksen." },
  mix: { imageAlt: "Karkea ja epätasainen taikina sekoituksen jälkeen", action: ["Lisää veteen jauhot ja hiiva valitun hiivatyypin ohjeen mukaan.", "Puristele ja kääntele 5–8 minuuttia, kunnes kuivia jauhotaskuja ei enää näy.", "Jätä taikina tässä vaiheessa karkeaksi ja tahmeaksi."], why: "Ensimmäisen sekoituksen tehtävä on kastella kaikki jauho. Sitko alkaa muodostua levon aikana itsestään, joten taikinaa ei tarvitse vielä pakottaa sileäksi.", ready: "Taikina näyttää kuvan tavoin repaleiselta, mutta kulhon pohjalla ei ole kuivaa jauhoa.", mistake: "Älä korjaa tahmeutta lisäämällä jauhoja. Se muuttaisi hydraation ja tekisi pizzasta kuivemman." },
  rest: { imageAlt: "Karkea taikina lepää kannellisessa astiassa", action: ["Kaavi taikina yhteen ja peitä astia tiiviisti.", "Anna levätä ohjeessa näkyvä aika huoneenlämmössä.", "Älä vaivaa tai avaa kantta levon aikana."], why: "Vesi ehtii imeytyä jauhoon ja gluteenin rakennuspalikat järjestyvät. Seuraava vaivaus on helpompi ja taikina repeää vähemmän.", ready: "Taikina tuntuu levon jälkeen pehmeämmältä ja venyy hieman paremmin kuin ennen lepoa.", mistake: "Peittämätön pinta kuivuu kalvoksi, joka tekee myöhemmin taikinaan kovia kohtia." },
  knead: { imageAlt: "Taikinan reuna venytetään ja taitetaan keskelle", action: ["Lisää suola; kostuta kädet kevyesti tarttumisen vähentämiseksi.", "Nosta taikinan reunaa varovasti, venytä vain vastukseen asti ja taita keskelle.", "Kierrä astiaa ja toista neljältä sivulta. Lepuuta 15 minuuttia ja tee tarvittaessa 2–3 kierrosta."], why: "Taittelu järjestää gluteenisäikeitä verkoksi, joka pitää hiivan tuottaman kaasun taikinassa. Lepo kierrosten välissä estää repeämisen.", ready: "Pinta on aiempaa sileämpi, taikina pitää muotonsa ja ohut venytetty kohta päästää valoa läpi repeämättä.", mistake: "Älä revi taikinaa tai jatka väkisin, kun se kiristyy. Peitä ja anna levätä 15 minuuttia." },
  bulk: { imageAlt: "Taikina on kasvanut läpinäkyvässä astiassa", action: ["Siirrä taikina suorareunaiseen, kevyesti öljyttyyn astiaan ja merkitse lähtökorkeus.", "Sulje kansi ja pidä lämpö mahdollisimman tasaisena.", "Seuraa kasvua ja kuplia – älä pelkkää kelloa."], why: "Massakohotuksessa maku kehittyy ja gluteeniverkko täyttyy kaasusta. Lähtökorkeuden merkki näyttää todellisen kasvun arvaamisen sijaan.", ready: "Taikina on ilmavampi, pinnaltaan hieman kupera ja noin 30–60 % lähtötilavuutta suurempi. Sen ei tarvitse kaksinkertaistua.", mistake: "Kaksinkertaiseksi odottaminen voi ylikohottaa taikinan, etenkin ennen pitkää kylmäkohotusta." },
  ball: { imageAlt: "Taikinapallon pinta kiristetään käsillä", action: ["Kumoa taikina varovasti ja jaa se vaa'alla yhtä suuriin paloihin.", "Taita palan reunat alle ja sulje sauma.", "Kuppaa kädet pallon ympärille ja vedä palloa kevyesti pöytää vasten, kunnes pinta kiristyy."], why: "Sileä, ehjä pinta toimii kuin ilmapallon kuori: se pitää kaasun sisällä ja auttaa pizzan reunaa kohoamaan uunissa.", ready: "Pallo on pyöreä ja pinta sileä sekä jäntevä, mutta siinä ei ole repeämiä. Sauma on alapuolella.", mistake: "Liiallinen kiristäminen repii pinnan. Lopeta heti, kun pallo pitää muotonsa." },
  cold: { imageAlt: "Kuusi taikinapalloa kannellisessa rasiassa jääkaapissa", action: ["Aseta pallot kannelliseen laatikkoon niin, että niiden ympärille jää kasvutilaa.", "Siirrä laatikko jääkaapin keskiosaan, noin 4 °C:een.", "Pidä kansi suljettuna koko kylmäkohotuksen ajan."], why: "Kylmä hidastaa hiivaa mutta antaa entsyymien kehittää makua ja avautuvuutta. Tasainen 4 °C tekee aikataulusta ennustettavan.", ready: "Pallot ovat hieman kasvaneet ja niissä näkyy pieniä kuplia, mutta ne eivät ole valuneet yhdeksi massaksi.", mistake: "Jääkaapin oven lämpö vaihtelee. Älä säilytä taikinaa ovessa äläkä muuta lämpöä käsin kesken ohjelman." },
  warm: { imageAlt: "Taikinan kypsyyttä kokeillaan kevyellä sormen painalluksella", action: ["Nosta suljettu taikinalaatikko huoneenlämpöön ohjeen osoittamana aikana.", "Pidä pallot peitettyinä ja vältä laatikon siirtelyä.", "Paina lopuksi jauhotetulla sormella hyvin kevyesti pallon sivua."], why: "Kylmä taikina vastustaa venytystä ja repeää helpommin. Lämpeneminen rentouttaa gluteenia ja käynnistää hiivan jälleen hallitusti.", ready: "Pallo on rento ja ilmava. Kevyt painauma palautuu hitaasti ja jää hieman näkyviin.", mistake: "Nopeasti kokonaan palautuva painauma kertoo usein alikohotuksesta; täysin painuva ja veltto pallo voi olla ylikohonnut." },
  final: { imageAlt: "Taikinan kypsyyttä kokeillaan kevyellä sormen painalluksella", action: ["Pidä pallot kannellisessa laatikossa tasaisessa huoneenlämmössä.", "Vältä vedon ja suoran auringon osumista laatikkoon.", "Tarkista valmius kevyellä sormen painalluksella."], why: "Pallokohotus rentouttaa pallot avaamista varten ja jakaa käymiskaasun tasaisesti valmiiseen reunukseen.", ready: "Pallo on ilmava, hieman levinnyt ja painauma palautuu hitaasti vain osittain.", mistake: "Kello on arvio. Kuuma huone nopeuttaa ja viileä huone hidastaa kohotusta." },
  bake: { imageAlt: "Pizzapohja avataan sormenpäillä keskeltä kohti reunaa", action: ["Kumoa pallo avausjauhoon ja käännä kerran. Siirrä se puhtaalle pöydälle.", "Paina sormenpäillä keskeltä ulospäin ja jätä 1–2 cm reunus koskematta.", "Venytä keskiosaa käsien päällä tavoitekokoon, täytä nopeasti ja siirrä heti kuumalle kivelle."], why: "Keskeltä ulospäin painaminen siirtää kaasua reunukseen. Koskematon reunus laajenee kuumassa uunissa; kaulin puristaisi kaasun pois.", ready: "Pohja on keskeltä tasaisen ohut, reuna on selvästi paksumpi eikä pinnassa ole repeämiä.", mistake: "Älä jätä täytettyä pizzaa lapion päälle odottamaan – kosteus tartuttaa sen nopeasti." },
};

const en: Record<string, Omit<BeginnerStepHelp, "image">> = {
  prepare: { imageAlt: "Flour, water, salt and yeast weighed separately", action: ["Place an empty bowl on the scale and tare it between ingredients.", "Weigh flour and water in grams, then weigh salt separately.", "Use a 0.01 g precision scale for yeast amounts below one gram."], why: "A few grams can change dough behaviour. Weighing makes the result repeatable; volume measures are not accurate enough.", ready: "All four ingredients are separate and every scale reading has been checked.", mistake: "Do not pour yeast straight from the packet—the excess can ruin a long fermentation." },
  mix: { imageAlt: "Rough uneven dough after initial mixing", action: ["Combine water, flour and yeast according to the selected yeast directions.", "Squeeze and fold for 5–8 minutes until no dry flour pockets remain.", "Leave the dough rough and sticky at this stage."], why: "The goal is to hydrate every particle of flour. Gluten begins forming during the rest, so the dough does not need to be forced smooth yet.", ready: "The dough is shaggy like the picture, but there is no dry flour at the bottom.", mistake: "Do not fix stickiness by adding flour. That changes hydration and makes the pizza drier." },
  rest: { imageAlt: "Rough dough resting in a covered container", action: ["Scrape the dough together and cover tightly.", "Rest for the stated time at room temperature.", "Do not knead or uncover it during the rest."], why: "Water absorbs into the flour and gluten building blocks organise themselves. Kneading becomes easier and the dough tears less.", ready: "After resting, the dough feels softer and stretches more easily.", mistake: "An uncovered surface dries into a skin that creates hard pieces later." },
  knead: { imageAlt: "The edge of the dough is stretched and folded inward", action: ["Add salt and wet your hands lightly to reduce sticking.", "Lift one edge, stretch only until resistance, and fold it over the centre.", "Turn the tub and repeat on four sides; rest 15 minutes and make 2–3 rounds if needed."], why: "Folding aligns gluten into a network that retains fermentation gas. Resting between rounds prevents tearing.", ready: "The surface is smoother, the dough holds shape, and a thin stretched section lets light through without tearing.", mistake: "Do not pull through strong resistance. Cover and rest for 15 minutes instead." },
  bulk: { imageAlt: "Dough has expanded in a clear straight-sided container", action: ["Move dough to a lightly oiled straight-sided tub and mark its starting height.", "Cover and keep the temperature as steady as possible.", "Watch expansion and bubbles, not only the clock."], why: "Bulk fermentation develops flavour and fills the gluten network with gas. A starting mark shows real growth instead of guesswork.", ready: "The dough is livelier, slightly domed and roughly 30–60% larger. It does not need to double.", mistake: "Waiting for it to double may overproof it, especially before a long cold ferment." },
  ball: { imageAlt: "A pizza dough ball is tightened by cupped hands", action: ["Turn the dough out gently and weigh equal portions.", "Fold the edges underneath and close the seam.", "Cup your hands around the piece and drag it gently until the surface tightens."], why: "The smooth intact surface works like a balloon skin: it holds gas and helps the rim rise in the oven.", ready: "The ball is round, smooth and taut without tears, with the seam underneath.", mistake: "Over-tightening tears the surface. Stop as soon as the ball holds its shape." },
  cold: { imageAlt: "Six covered dough balls in a refrigerator", action: ["Place the balls in a covered box with room around each one.", "Put the box in the middle of a refrigerator at about 4°C.", "Keep the lid closed throughout the cold ferment."], why: "Cold slows yeast while enzymes continue developing flavour and extensibility. A stable 4°C makes timing predictable.", ready: "The balls have grown slightly and show small bubbles without flowing into one mass.", mistake: "The refrigerator door changes temperature. Do not store dough there or alter the temperature during the programme." },
  warm: { imageAlt: "Dough readiness tested with a gentle fingertip press", action: ["Move the closed dough box to room temperature at the scheduled time.", "Keep the balls covered and avoid moving the box.", "Finally press the side lightly with a floured fingertip."], why: "Cold dough resists stretching and tears more easily. Warming relaxes gluten and restarts yeast in a controlled way.", ready: "The ball is relaxed and airy; a shallow indentation returns slowly and remains faintly visible.", mistake: "A fast rebound often means underproofing; a completely collapsing slack ball may be overproofed." },
  final: { imageAlt: "Dough readiness tested with a gentle fingertip press", action: ["Keep balls in a covered box at a steady room temperature.", "Avoid draughts and direct sunlight.", "Check readiness with a gentle fingertip press."], why: "Ball proofing relaxes the dough for opening and distributes fermentation gas into the future rim.", ready: "The ball is airy, slightly spread, and the indentation returns slowly only partway.", mistake: "Time is an estimate. A warm room speeds proofing and a cool room slows it." },
  bake: { imageAlt: "Pizza dough opened with fingertips from the centre outward", action: ["Turn the ball into opening flour once, then move it to a clean bench.", "Press from the centre outward, leaving a 1–2 cm rim untouched.", "Stretch the centre to size, top quickly and launch immediately."], why: "Pressing outward moves gas into the rim. The untouched rim expands in the oven; a rolling pin would squeeze the gas out.", ready: "The centre is evenly thin, the rim clearly thicker, and the surface has no tears.", mistake: "Do not leave a topped pizza waiting on the peel—moisture makes it stick quickly." },
};

export function beginnerHelpFor(id: string, locale: InstructionLocale): BeginnerStepHelp {
  const localized = (locale === "fi" ? fi : en)[id] ?? fi[id];
  return { image: imageByStep[id] ?? imageByStep.prepare, ...localized };
}
