import type { RecipeSettings } from "@/lib/saved-recipes";

export type CommunityStyle = "neapolitan" | "airy" | "home" | "crisp" | "pan";
export type CommunityRecipe = {
  id: string; nameFi: string; nameEn: string; descriptionFi: string; descriptionEn: string;
  sourceFi: string; sourceEn: string; style: CommunityStyle; image: string; difficulty: 1 | 2 | 3;
  settings: RecipeSettings;
};

const base = { pizzas: 6, waste: 3, salt: 2.8, yeastType: "idy" as const };

export const communityRecipes: CommunityRecipe[] = [
  { id: "classic-naples", nameFi: "Klassinen Napoli", nameEn: "Classic Naples", descriptionFi: "Hallittava, pehmeä ja nopeasti paistuva napolilainen lähtöresepti.", descriptionEn: "A manageable, soft and fast-baking Neapolitan starting recipe.", sourceFi: "Napolilainen perusasetelma", sourceEn: "Neapolitan community baseline", style: "neapolitan", image: "/pizza-styles/neapolitan.webp", difficulty: 2, settings: { ...base, ballWeight: 260, hydration: 64, fermentation: "12h-room", temperature: 22, goal: "balanced", ovenType: "gas", flourId: "caputo-pizzeria" } },
  { id: "weekend-canotto", nameFi: "Viikonlopun canotto", nameEn: "Weekend canotto", descriptionFi: "Korkea, kevyt reuna vahvalla jauholla ja pitkällä kylmäkohotuksella.", descriptionEn: "A tall light rim using strong flour and long cold fermentation.", sourceFi: "Ilmavien reunojen harrastajat", sourceEn: "Airy-rim community setup", style: "airy", image: "/pizza-styles/contemporary.webp", difficulty: 3, settings: { ...base, ballWeight: 270, hydration: 72, fermentation: "48h-cold", temperature: 4, goal: "airy", ovenType: "gas", flourId: "caputo-nuvola-super" } },
  { id: "home-oven-friday", nameFi: "Perjantain keittiöuunipizza", nameEn: "Friday home-oven pizza", descriptionFi: "Helppo samana päivänä tehtävä pizza teräkselle tai kivelle.", descriptionEn: "An easy same-day pizza for a home baking steel or stone.", sourceFi: "Kotiuunien perusasetelma", sourceEn: "Home-oven community baseline", style: "home", image: "/pizza-styles/new-york.webp", difficulty: 1, settings: { ...base, ballWeight: 280, hydration: 62, fermentation: "6h-room", temperature: 22, goal: "balanced", ovenType: "home", flourId: "caputo-classica" } },
  { id: "new-york-48", nameFi: "48 tunnin New York", nameEn: "48-hour New York", descriptionFi: "Taipuisa pala, paahteinen pohja ja pitkä jääkaappimaku.", descriptionEn: "A foldable slice, toasted base and deep refrigerator flavour.", sourceFi: "New York -tyylin harrastajat", sourceEn: "New York-style community setup", style: "home", image: "/pizza-styles/new-york.webp", difficulty: 2, settings: { ...base, ballWeight: 320, hydration: 65, salt: 2.5, fermentation: "48h-cold", temperature: 4, goal: "balanced", ovenType: "home", flourId: "caputo-cuoco" } },
  { id: "roman-crunch", nameFi: "Roomalainen rouske", nameEn: "Roman crunch", descriptionFi: "Ohut, kuiva ja rapea tonda ilman suurta reunusta.", descriptionEn: "A thin, dry and crisp tonda with no large rim.", sourceFi: "Tonda romana -asetelma", sourceEn: "Tonda romana community setup", style: "crisp", image: "/pizza-styles/roman-thin.webp", difficulty: 2, settings: { ...base, ballWeight: 220, hydration: 58, salt: 2.5, fermentation: "24h-cold", temperature: 4, goal: "crispy", ovenType: "home", flourId: "caputo-pizzeria" } },
  { id: "soft-nordic", nameFi: "Pehmeä pohjoismainen", nameEn: "Soft Nordic", descriptionFi: "Maltillisen ilmava pizza, joka toimii kylmässä ilmastossa ennustettavasti.", descriptionEn: "A gently airy pizza designed for predictable cold-climate baking.", sourceFi: "Pohjoismaisten kotileipurien asetelma", sourceEn: "Nordic home-baker setup", style: "airy", image: "/pizza-styles/neapolitan.webp", difficulty: 2, settings: { ...base, ballWeight: 270, hydration: 68, fermentation: "24h-cold", temperature: 4, goal: "airy", ovenType: "gas", flourId: "caputo-nuvola" } },
  { id: "detroit-party", nameFi: "Detroit-juhlapannu", nameEn: "Detroit party pan", descriptionFi: "Paksu ilmava pannupizza rapealla, karamellisoituneella juustoreunalla.", descriptionEn: "A thick airy pan pizza with a crisp caramelised cheese edge.", sourceFi: "Pannupizzayhteisön asetelma", sourceEn: "Pan-pizza community setup", style: "pan", image: "/pizza-styles/detroit.webp", difficulty: 2, settings: { ...base, pizzas: 1, ballWeight: 650, hydration: 75, salt: 2.5, fermentation: "48h-cold", temperature: 4, goal: "pan", ovenType: "home", flourId: "caputo-nuvola-super" } },
  { id: "sicilian-family", nameFi: "Sisilialainen perhepelti", nameEn: "Sicilian family tray", descriptionFi: "Pehmeä, öljyinen ja helposti jaettava suorakulmainen pizza.", descriptionEn: "A soft, oil-crisped rectangular pizza made for sharing.", sourceFi: "Sisilialaisen pannupizzan asetelma", sourceEn: "Sicilian pan community setup", style: "pan", image: "/pizza-styles/sicilian.webp", difficulty: 1, settings: { ...base, pizzas: 1, ballWeight: 750, hydration: 70, salt: 2.5, fermentation: "24h-room", temperature: 22, goal: "pan", ovenType: "home", flourId: "caputo-cuoco" } },
];

export type LocalCommunityRecipe = { id: string; createdAt: string; title: string; creator: string; note: string; settings: RecipeSettings };
const STORAGE_KEY = "doughtools-community-recipes-v1";
export function loadLocalCommunityRecipes(): LocalCommunityRecipe[] { try { const value = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "[]"); return Array.isArray(value) ? value : []; } catch { return []; } }
export function saveLocalCommunityRecipes(recipes: LocalCommunityRecipe[]) { localStorage.setItem(STORAGE_KEY, JSON.stringify(recipes)); }
