export type OvenBudget = "starter" | "mid" | "premium";
export type OvenPlace = "indoor" | "outdoor" | "either";
export type OvenPriority = "easy" | "portable" | "performance";

export type OvenProfile = {
  id: string; name: string; maker: string; icon: string;
  budget: OvenBudget; place: Exclude<OvenPlace, "either">; priorities: OvenPriority[];
  price: string; fuel: string; size: string; heat: string; bake: string;
  score: { ease: number; portability: number; performance: number; value: number };
  goodFi: string[]; badFi: string[]; goodEn: string[]; badEn: string[];
  bestFi: string; bestEn: string; avoidFi: string; avoidEn: string; source: string;
};

export const ovens: OvenProfile[] = [
  { id: "chef-matteo-crosta", name: "Crosta 16\"", maker: "Chef Matteo", icon: "◉", budget: "mid", place: "outdoor", priorities: ["easy", "performance"], price: "noin 399 €", fuel: "Kaasu", size: "16\" / noin 40 cm", heat: "noin 450–500 °C", bake: "60–120 s", score: { ease: 5, portability: 3, performance: 4, value: 5 }, goodFi: ["Pyörivä pizzakivi helpottaa tasaista paistoa", "U-muotoinen poltin ympäröi pizzaa lämmöllä", "Kilpailukykyinen hinta 16 tuuman uunille"], badFi: ["Painavampi kuin pienet kannettavat uunit", "Myynti ja tuki painottuvat Power-ketjuun", "Pyörivä mekanismi lisää liikkuvia osia"], goodEn: ["Rotating stone makes even baking easier", "U-shaped burner surrounds the pizza with heat", "Competitive price for a 16-inch oven"], badEn: ["Heavier than compact portable ovens", "Sales and support centre on the Power chain", "Rotating mechanism adds moving parts"], bestFi: "Kun haluat suuren ja helpon kaasuuunin hyvällä vastineella Suomessa.", bestEn: "A large easy gas oven with strong value in the Nordic market.", avoidFi: "Jos haluat mahdollisimman kevyen uunin tai laajan jälleenmyyjäverkoston.", avoidEn: "If you want minimum weight or a broad dealer network.", source: "https://www.power.fi/koti-ja-piha/piha-ja-vapaa-aika/pizzan-valmistus/pizzauunit/chef-matteo-crosta-16-pizzauuni-kaasukayttoinen/p-2713284/" },
  { id: "home-steel", name: "Keittiöuuni + paistoteräs", maker: "Nykyinen uunisi", icon: "▰", budget: "starter", place: "indoor", priorities: ["easy", "performance"], price: "60–180 €", fuel: "Sähkö", size: "Uunin oma leveys", heat: "250–300 °C", bake: "4–8 min", score: { ease: 5, portability: 1, performance: 3, value: 5 }, goodFi: ["Halvin järkevä aloitus", "Toimii ympäri vuoden", "Loistava New York- ja pannupizzalle"], badFi: ["Ei aitoa 90 sekunnin napolilaista", "Teräs vaatii pitkän esilämmityksen", "Ylälämpö voi jäädä jälkeen"], goodEn: ["Best low-cost start", "Works year-round", "Excellent for New York and pan pizza"], badEn: ["Not true 90-second Neapolitan", "Steel needs a long preheat", "Top heat may lag behind"], bestFi: "Ensimmäiseksi hankinnaksi ja monipuoliseen kotipizzaan.", bestEn: "A first purchase and versatile home pizza.", avoidFi: "Kun tavoitteena on vain napolilainen 60–90 sekunnissa.", avoidEn: "When the only goal is 60–90 second Neapolitan.", source: "https://www.pizzamaking.com/forum/index.php?board=1.0" },
  { id: "cozze-13", name: "Cozze 13\"", maker: "Cozze", icon: "◒", budget: "starter", place: "outdoor", priorities: ["easy", "portable"], price: "200–300 €", fuel: "Kaasu", size: "13\" / noin 34 cm", heat: "jopa noin 450 °C", bake: "90–120 s", score: { ease: 4, portability: 4, performance: 3, value: 5 }, goodFi: ["Edullinen ja yleinen Pohjoismaissa", "Yksinkertainen kaasukäyttö", "Pieni säilyttää"], badFi: ["Ahdas aukko aloittelijalle", "Lämmön tasaisuus vaatii kääntämistä", "Viimeistely perustasoa"], goodEn: ["Affordable and common in the Nordics", "Simple gas operation", "Compact to store"], badEn: ["Tight opening for beginners", "Needs active turning", "Basic finish"], bestFi: "Pienellä budjetilla ensimmäiseksi ulkouuniksi.", bestEn: "A first outdoor oven on a small budget.", avoidFi: "Jos haluat suuria pizzoja tai paljon tilaa lapion käyttöön.", avoidEn: "If you want large pizzas or lots of room for the peel.", source: "https://cozze-pizza.com/" },
  { id: "ooni-koda-2", name: "Koda 2", maker: "Ooni", icon: "◓", budget: "mid", place: "outdoor", priorities: ["easy", "portable", "performance"], price: "400–550 €", fuel: "Kaasu", size: "14\" / noin 36 cm", heat: "jopa 500 °C", bake: "60–90 s", score: { ease: 5, portability: 4, performance: 4, value: 4 }, goodFi: ["Helppo sytyttää ja säätää", "Hyvä varaosa- ja tarvikevalikoima", "Tasaisempi liekki kuin pienissä perusmalleissa"], badFi: ["Vain ulkokäyttöön", "Kääntäminen täytyy opetella", "Kaasupullo ja suojus lisäävät hintaa"], goodEn: ["Easy ignition and control", "Strong accessory ecosystem", "More even flame than small entry models"], badEn: ["Outdoor only", "Turning takes practice", "Gas bottle and cover add cost"], bestFi: "Useimmille helpoin laadukas kaasuuuni.", bestEn: "The easiest quality gas oven for most people.", avoidFi: "Jos haluat puun rituaalin tai sisäkäytön.", avoidEn: "If you want wood-fire ritual or indoor use.", source: "https://eu.ooni.com/products/ooni-koda-2" },
  { id: "gozney-tread", name: "Tread", maker: "Gozney", icon: "⬡", budget: "mid", place: "outdoor", priorities: ["portable", "performance"], price: "500–650 €", fuel: "Kaasu", size: "12\" / noin 31 cm", heat: "jopa 500 °C", bake: "60–90 s", score: { ease: 4, portability: 5, performance: 4, value: 3 }, goodFi: ["Todella siirrettävä rakenne", "Tehokas kokoonsa nähden", "Hyvä retkille ja parvekkeen sijasta pihalle"], badFi: ["Pieni paistoala", "Jalusta ja tarvikkeet nostavat hintaa", "Ei paras kuuden pizzan sarjatyöhön"], goodEn: ["Genuinely portable", "Powerful for its size", "Strong travel setup"], badEn: ["Small cooking area", "Stand and accessories raise cost", "Not ideal for six-pizza production"], bestFi: "Kun uuni kulkee mökille, matkalle tai varastoon.", bestEn: "When the oven travels to a cabin, trip or storage.", avoidFi: "Jos paistat isoja pizzoja tai suuria eriä.", avoidEn: "If you bake large pizzas or large batches.", source: "https://www.gozney.com/products/tread" },
  { id: "witt-rotante", name: "ETNA Rotante", maker: "Witt", icon: "◎", budget: "premium", place: "outdoor", priorities: ["easy", "performance"], price: "700–900 €", fuel: "Kaasu", size: "16\" / noin 40 cm", heat: "jopa 500 °C", bake: "60–90 s", score: { ease: 5, portability: 2, performance: 4, value: 4 }, goodFi: ["Pyörivä kivi vähentää stressiä", "Tilava suuaukko", "Erillinen pohjapoltin auttaa kiven lämmössä"], badFi: ["Painava ja kookas", "Liikkuvia osia enemmän", "Ei tarjoa puun makua tai rituaalia"], goodEn: ["Rotating stone lowers stress", "Wide opening", "Booster burner supports stone heat"], badEn: ["Heavy and bulky", "More moving parts", "No wood-fire ritual"], bestFi: "Helppoutta arvostavalle, joka paistaa usein monta pizzaa.", bestEn: "For easy, frequent multi-pizza sessions.", avoidFi: "Jos uunia täytyy kantaa joka käyttökerralla.", avoidEn: "If the oven must be carried every session.", source: "https://www.wittpizza.com/" },
  { id: "gozney-arc-xl", name: "Arc XL", maker: "Gozney", icon: "◐", budget: "premium", place: "outdoor", priorities: ["performance"], price: "850–1 050 €", fuel: "Kaasu", size: "16\" / noin 40 cm", heat: "jopa 500 °C", bake: "60–90 s", score: { ease: 4, portability: 2, performance: 5, value: 3 }, goodFi: ["Tilava ja näkyvä paistoalue", "Voimakas sivuliekki", "Hyvä lämmön palautuminen sarjapaistossa"], badFi: ["Painava", "Jalusta myydään usein erikseen", "Sivuliekki vaatii pizzan tarkkailua"], goodEn: ["Spacious visible cooking floor", "Powerful side flame", "Good recovery for consecutive pizzas"], badEn: ["Heavy", "Stand often sold separately", "Side flame demands attention"], bestFi: "Vakavalle harrastajalle, joka haluaa tilaa ja suorituskykyä.", bestEn: "For a serious enthusiast wanting space and performance.", avoidFi: "Kun budjetti tai säilytystila on rajallinen.", avoidEn: "When budget or storage is limited.", source: "https://www.gozney.com/products/arc-xl" },
  { id: "effeuno-p134h", name: "P134H 509", maker: "Effeuno", icon: "⚡", budget: "premium", place: "indoor", priorities: ["performance"], price: "900–1 300 €", fuel: "Sähkö", size: "noin 34 cm", heat: "jopa 509 °C", bake: "60–120 s", score: { ease: 3, portability: 1, performance: 5, value: 4 }, goodFi: ["Napolilainen sisällä ympäri vuoden", "Ylä- ja alalämpö erikseen", "Hiljainen eikä kaasupulloa"], badFi: ["Painava ammattimainen laite", "Sähkökuorma ja sijoitus tarkistettava", "Oppimiskäyrä ja korkea hinta"], goodEn: ["Indoor Neapolitan year-round", "Separate top and bottom heat", "Quiet with no gas bottle"], badEn: ["Heavy specialist appliance", "Electrical load and placement need checking", "Learning curve and high price"], bestFi: "Suomen talveen ja vaativaan sisäpaistoon.", bestEn: "Finnish winters and demanding indoor baking.", avoidFi: "Jos haluat vain vaivattoman satunnaisuunin.", avoidEn: "If you only want an effortless occasional oven.", source: "https://www.effeuno.biz/en/" },
  { id: "gozney-dome", name: "Dome", maker: "Gozney", icon: "◉", budget: "premium", place: "outdoor", priorities: ["performance"], price: "1 500–2 200 €", fuel: "Kaasu / mallista riippuen puu", size: "suuri kupu-uuni", heat: "jopa 500 °C", bake: "60–90 s", score: { ease: 3, portability: 1, performance: 5, value: 2 }, goodFi: ["Suuri lämpömassa", "Pizzaa laajempi ruoanlaitto", "Näyttävä pysyvä ulkokeittiön keskus"], badFi: ["Erittäin painava ja kallis", "Tarvitsee pysyvän paikan", "Ylimitoitettu satunnaiseen käyttöön"], goodEn: ["Large thermal mass", "Cooking beyond pizza", "A striking outdoor-kitchen centrepiece"], badEn: ["Very heavy and expensive", "Needs a permanent location", "Overkill for occasional use"], bestFi: "Pysyvään ulkokeittiöön ja monipuoliseen tulella kokkaamiseen.", bestEn: "A permanent outdoor kitchen and broader live-fire cooking.", avoidFi: "Jos tärkeintä on vain hyvä pizza pienellä vaivalla.", avoidEn: "If you only need great pizza with minimal fuss.", source: "https://www.gozney.com/products/dome" },
];

export function recommendOvens(budget: OvenBudget, place: OvenPlace, priority: OvenPriority) {
  const budgetRank = { starter: 0, mid: 1, premium: 2 };
  return ovens.map((oven) => {
    const affordable = budgetRank[oven.budget] <= budgetRank[budget];
    const location = place === "either" || oven.place === place;
    const scoreKey = priority === "easy" ? "ease" : priority === "portable" ? "portability" : "performance";
    const priorityScore = oven.score[scoreKey];
    return { oven, points: (affordable ? 5 : -5) + (location ? 5 : -8) + priorityScore + oven.score.value / 2 };
  }).sort((a, b) => b.points - a.points).slice(0, 3).map(({ oven }) => oven);
}
