export type GearTier = "essential" | "useful" | "later";
export type GearCategory = "dough" | "launch" | "bake" | "serve" | "safety";
export type GearItem = { id: string; icon: string; tier: GearTier; category: GearCategory; price: string; nameFi: string; nameEn: string; whyFi: string; whyEn: string; chooseFi: string; chooseEn: string; mistakeFi: string; mistakeEn: string };

export const gearItems: GearItem[] = [
  { id: "scale", icon: "⚖", tier: "essential", category: "dough", price: "15–40 €", nameFi: "Digitaalivaaka", nameEn: "Digital scale", whyFi: "Pallopaino, hydraatio ja suola pysyvät toistettavina.", whyEn: "Keeps ball weight, hydration and salt repeatable.", chooseFi: "Vähintään 1 g tarkkuus ja 5 kg kapasiteetti. Hiivalle erillinen 0,01 g tarkkuusvaaka on hyödyllinen.", chooseEn: "At least 1 g resolution and 5 kg capacity. A separate 0.01 g scale helps with yeast.", mistakeFi: "Älä mittaa jauhoa tilavuusmitalla.", mistakeEn: "Do not measure flour by volume." },
  { id: "proof-box", icon: "▣", tier: "essential", category: "dough", price: "10–35 €", nameFi: "Kannellinen kohotuslaatikko", nameEn: "Lidded proofing box", whyFi: "Estää pallojen kuivumisen ja helpottaa niiden nostamista.", whyEn: "Prevents skinning and makes dough balls easier to lift.", chooseFi: "Elintarvikekelpoinen, matala laatikko tai yksittäiset pyöreät astiat. Jätä pallojen väliin kasvutilaa.", chooseEn: "Food-safe shallow tray or individual round tubs, with room for expansion.", mistakeFi: "Liian pieni astia liimaa pallot toisiinsa.", mistakeEn: "A cramped box makes the balls merge." },
  { id: "scraper", icon: "▰", tier: "essential", category: "dough", price: "5–15 €", nameFi: "Taikinalasta", nameEn: "Dough scraper", whyFi: "Irrottaa pallon astiasta rikkomatta ilmavaa rakennetta.", whyEn: "Releases dough without destroying its airy structure.", chooseFi: "Joustava muovilasta astialle ja tukeva metallilasta taikinan jakamiseen.", chooseEn: "Flexible plastic for tubs and a firm metal scraper for dividing dough.", mistakeFi: "Älä vedä palloa sormilla väkisin ylöspäin.", mistakeEn: "Do not pull the ball upward by force." },
  { id: "launch-peel", icon: "━", tier: "essential", category: "launch", price: "30–100 €", nameFi: "Lähtölapio", nameEn: "Launching peel", whyFi: "Siirtää täytetyn pizzan pöydältä kuumalle kivelle.", whyEn: "Moves the topped pizza from the station to the hot stone.", chooseFi: "Puu tarttuu usein vähiten aloittelijalla; ohut rei'itetty alumiini pudottaa ylimääräistä jauhoa. Lapion täytyy mahtua uunin aukosta.", chooseEn: "Wood often sticks least for beginners; thin perforated aluminium sheds excess flour. It must fit the oven opening.", mistakeFi: "Älä jätä täytettyä pizzaa odottamaan lapion päälle.", mistakeEn: "Do not leave a topped pizza waiting on the peel." },
  { id: "thermometer", icon: "◉", tier: "essential", category: "bake", price: "20–50 €", nameFi: "Infrapunalämpömittari", nameEn: "Infrared thermometer", whyFi: "Uunin ilman lämpö ei kerro, onko kivi valmis seuraavalle pizzalle.", whyEn: "Air temperature does not tell whether the stone is ready.", chooseFi: "Mittausalue vähintään 550 °C ja selkeä tähtäys. Mittaa aina samasta kohdasta.", chooseEn: "At least a 550°C range and clear aiming. Measure the same spot each time.", mistakeFi: "Älä luota pelkkään uunin kannen mittariin.", mistakeEn: "Do not rely only on a dome thermometer." },
  { id: "turning-peel", icon: "◌", tier: "useful", category: "bake", price: "25–80 €", nameFi: "Kääntölapio", nameEn: "Turning peel", whyFi: "Kääntää pizzan nopeasti ilman, että uunin lämpö karkaa.", whyEn: "Turns pizza quickly without losing oven heat.", chooseFi: "Noin 18–23 cm pyöreä, ohut lapa ja uuniin sopiva varren pituus.", chooseEn: "A thin 18–23 cm round head and a handle suited to the oven depth.", mistakeFi: "Nosta pizzaa hieman ennen kääntöä – älä työnnä täytteiden läpi.", mistakeEn: "Lift slightly before turning; do not push through toppings." },
  { id: "prep-table", icon: "▤", tier: "useful", category: "launch", price: "40–250 €", nameFi: "Tukeva työpöytä", nameEn: "Stable prep table", whyFi: "Antaa puhtaan paikan avaamiseen, täyttämiseen ja lapion suoralle liikkeelle.", whyEn: "Provides a clean area for opening, topping and a straight peel movement.", chooseFi: "Sileä elintarvikekelpoinen pinta, vähintään pizzan ja lapion mittainen, suunnilleen vyötärön korkeudella.", chooseEn: "A smooth food-safe surface long enough for pizza and peel, near waist height.", mistakeFi: "Heiluva pieni sivupöytä tekee nostosta vaikean.", mistakeEn: "A small wobbly table makes launching harder." },
  { id: "flour-tub", icon: "□", tier: "useful", category: "dough", price: "5–20 €", nameFi: "Avausjauhoastia", nameEn: "Opening-flour tray", whyFi: "Pallo voidaan jauhottaa tasaisesti ennen avaamista.", whyEn: "Lets the dough ball be coated evenly before opening.", chooseFi: "Matala leveä astia. Käytä jauhoa tai hienon semolan ja jauhon seosta maltillisesti.", chooseEn: "A wide shallow tray. Use flour or a fine semolina-flour blend sparingly.", mistakeFi: "Liika karkea semola palaa ja maistuu kitkerältä.", mistakeEn: "Too much coarse semolina burns and tastes bitter." },
  { id: "landing-rack", icon: "▥", tier: "useful", category: "serve", price: "10–35 €", nameFi: "Jäähdytysritilä ja leikkuulauta", nameEn: "Cooling rack and cutting board", whyFi: "Lyhyt lepo ritilällä päästää höyryn pois ja säilyttää pohjan rapeampana.", whyEn: "A short rack rest releases steam and keeps the base crisper.", chooseFi: "Pizzaa suurempi ritilä sekä erillinen puu- tai muovilauta leikkaamiseen.", chooseEn: "A rack larger than the pizza plus a separate wood or plastic cutting board.", mistakeFi: "Älä leikkaa pizzaa metallilapion päällä.", mistakeEn: "Do not cut pizza on the metal peel." },
  { id: "cutter", icon: "✂", tier: "useful", category: "serve", price: "10–35 €", nameFi: "Leikkuri tai pizzakset", nameEn: "Wheel or pizza scissors", whyFi: "Jakaa pizzan painamatta ilmavaa reunaa kasaan.", whyEn: "Portions pizza without crushing the airy rim.", chooseFi: "Tukeva terävä rulla tai irrotettavat, pestävät pizzakset.", chooseEn: "A sturdy sharp wheel or separable washable pizza scissors.", mistakeFi: "Tylsä rulla vetää täytteet mukanaan.", mistakeEn: "A blunt wheel drags toppings away." },
  { id: "brush", icon: "⌁", tier: "later", category: "bake", price: "15–45 €", nameFi: "Kiviharja ja kaavin", nameEn: "Stone brush and scraper", whyFi: "Poistaa palaneen jauhon seuraavien pizzojen alta.", whyEn: "Removes burnt flour before the next pizza.", chooseFi: "Pitkävartinen, uunin valmistajan hyväksymä harja tai kaavin. Vältä irtoavia metalliharjaksia.", chooseEn: "A long-handled maker-approved brush or scraper. Avoid shedding wire bristles.", mistakeFi: "Älä kaada vettä kuumalle pizzakivelle.", mistakeEn: "Never pour water onto a hot stone." },
  { id: "precision-scale", icon: "·g", tier: "essential", category: "dough", price: "15–35 €", nameFi: "0,01 g tarkkuusvaaka", nameEn: "0.01 g precision scale", whyFi: "Pitkän kohotuksen alle gramman hiivamäärä voidaan mitata luotettavasti.", whyEn: "Measures sub-gram yeast amounts reliably for long fermentation.", chooseFi: "Valitse 0,01 g näyttötarkkuus, kalibrointitoiminto ja suojakansi. Punnitusalueeksi riittää yleensä 100–500 g.", chooseEn: "Choose 0.01 g resolution, calibration and a protective lid. A 100–500 g capacity is usually enough.", mistakeFi: "Tavallinen keittiövaaka voi näyttää 0 g, vaikka hiivaa on jo liikaa pitkään kohotukseen.", mistakeEn: "A kitchen scale may show 0 g even when there is already too much yeast for a long ferment." },
  { id: "cover", icon: "⌂", tier: "later", category: "safety", price: "25–80 €", nameFi: "Suoja ja säilytysratkaisu", nameEn: "Cover and storage", whyFi: "Suojaa kaasuliitännät, polttimen ja rungon Suomen säältä.", whyEn: "Protects gas fittings, burner and body from Nordic weather.", chooseFi: "Hengittävä oikean kokoinen suoja; uunin pitää olla täysin kylmä ja kuiva.", chooseEn: "A breathable fitted cover; the oven must be fully cool and dry.", mistakeFi: "Märän uunin peittäminen voi vangita kosteuden.", mistakeEn: "Covering a wet oven can trap moisture." },
  { id: "safety", icon: "!", tier: "essential", category: "safety", price: "20–60 €", nameFi: "Sammutuspeite ja kuumuudenkestävät käsineet", nameEn: "Fire blanket and heat gloves", whyFi: "Kuuma uuni, liekki ja rasva vaativat selkeän varautumisen.", whyEn: "A hot oven, flame and fat require basic preparation.", chooseFi: "CE-merkitty sammutuspeite helposti saavutettavaksi ja käsineet kuumien osien käsittelyyn.", chooseEn: "An approved fire blanket within reach and gloves for hot components.", mistakeFi: "Kaasupizzauunia ei koskaan käytetä sisällä tai suljetussa tilassa.", mistakeEn: "Never use a gas pizza oven indoors or in an enclosed area." },
];
