import type { DoughToolsIconName } from "@/components/icons";

export type PizzaStyleEducationId =
  | "neapolitan"
  | "contemporary-neapolitan"
  | "new-york"
  | "detroit"
  | "roman-tonda"
  | "roman-al-taglio"
  | "sicilian";

export type PizzaStyleSupport = "supported" | "learning";

export type PizzaStyleImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  fileSizeBytes: number;
  audit: string;
};

export type PizzaStyleEducation = {
  id: PizzaStyleEducationId;
  name: string;
  shortName: string;
  origin: string;
  icon: DoughToolsIconName;
  support: PizzaStyleSupport;
  supportNote: string;
  description: string;
  image?: PizzaStyleImage;
  shape: string;
  thickness: string;
  edge: string;
  interior: string;
  base: string;
  bakingSurface: string;
  ovenEnvironment: string;
  bakeStyle: string;
  cheeseTreatment: string;
  sauceTreatment: string;
  toppingDensity: string;
  eatingExperience: string;
  whatYouSee: readonly string[];
  whatYouFeel: readonly string[];
  whyItBehaves: string;
  typicalBuild: readonly string[];
  bestSuitedFor: readonly string[];
  commonConfusion: string;
  relatedLearning: readonly { href: string; title: string; description: string; icon: DoughToolsIconName }[];
};

export const plannerSupportedPizzaStyleIds = ["neapolitan"] as const;

export const pizzaStyleSupportSummary =
  "DoughTools Pizza Session currently plans Neapolitan-style pizza for home ovens and pizza ovens. Other styles here are educational learning guides; their separate dough, pan, oven and bake logic is not generated by Pizza Session yet.";

const sharedRelated = {
  dough: { href: "/guides/dough", title: "Dough Guide", description: "Follow the dough process step by step.", icon: "mixing-bowl" as const },
  sauce: { href: "/sauce", title: "Pizza Sauce", description: "Match tomato method and moisture to the style.", icon: "water" as const },
  ovens: { href: "/ovens", title: "Oven Guide", description: "Understand heat, surface and bake-time tradeoffs.", icon: "oven" as const },
  toppings: { href: "/toppings", title: "Toppings", description: "Control cheese, sauce and topping load.", icon: "pizza" as const },
  flour: { href: "/guide#flour-strength", title: "Flour strength", description: "Learn how flour strength affects structure.", icon: "wheat" as const },
  hydration: { href: "/guide#hydration", title: "Hydration", description: "See how water changes handling and texture.", icon: "water" as const },
  troubleshooting: { href: "/guide/pizza-troubleshooting", title: "Troubleshooting", description: "Diagnose sticky dough, dense crust or soft base.", icon: "warning" as const },
  gear: { href: "/gear", title: "Gear", description: "Choose pans, stones, steels and launching tools.", icon: "shopping-basket" as const },
};

export const pizzaStyleEducation: readonly PizzaStyleEducation[] = [
  {
    id: "neapolitan",
    name: "Neapolitan",
    shortName: "Neapolitan",
    origin: "Naples, Italy",
    icon: "pizza",
    support: "supported",
    supportNote: "Supported in Pizza Session",
    description: "A round personal pizza with a soft center, raised cornicione and very fast high-heat bake.",
    image: {
      src: "/pizza-styles/neapolitan.webp",
      alt: "Neapolitan pizza with a raised spotted cornicione, soft center, tomato, mozzarella and basil.",
      width: 900,
      height: 900,
      fileSizeBytes: 154726,
      audit: "Retain: accurate round geometry, raised rim, restrained topping and strong mobile crop.",
    },
    shape: "Round personal pizza",
    thickness: "Thin center with a raised rim",
    edge: "Soft, elastic cornicione",
    interior: "Tender, airy rim with a soft center",
    base: "Soft rather than cracker-crisp",
    bakingSurface: "Very hot stone or oven floor",
    ovenEnvironment: "High-heat pizza oven",
    bakeStyle: "Fast, usually around 60–90 seconds in the formal reference environment",
    cheeseTreatment: "Fresh mozzarella or fior di latte in restrained pieces",
    sauceTreatment: "Fresh tomato base used lightly",
    toppingDensity: "Restrained",
    eatingExperience: "Soft, light, aromatic and eaten soon after baking",
    whatYouSee: ["Round pizza", "Raised spotted rim", "Thin center", "Light tomato and mozzarella coverage"],
    whatYouFeel: ["Soft center", "Elastic chew", "Airy rim", "Fast-cooked freshness"],
    whyItBehaves:
      "The hot oven expands the rim quickly while restrained toppings keep the center from becoming heavy. A longer lower-heat bake would dry the dough and change the topping behavior.",
    typicalBuild: ["Fresh tomato base", "Fresh mozzarella or fior di latte", "Basil and olive oil as part of the topping profile", "Hand-stretched dough"],
    bestSuitedFor: ["Very hot pizza ovens", "Small personal pizzas", "Light topping balance", "Learning dough readiness and launch timing"],
    commonConfusion:
      "A home-oven pizza can be Neapolitan-inspired, but it is not formally AVPN-compliant unless the regulated process and oven environment are met.",
    relatedLearning: [sharedRelated.sauce, sharedRelated.ovens, sharedRelated.dough, sharedRelated.flour, sharedRelated.toppings],
  },
  {
    id: "contemporary-neapolitan",
    name: "Contemporary Neapolitan",
    shortName: "Contemporary",
    origin: "Modern Neapolitan movement",
    icon: "experience-level",
    support: "learning",
    supportNote: "Learning guide",
    description: "A modern family of Neapolitan-inspired approaches, often with a more expressive rim and open internal structure.",
    image: {
      src: "/pizza-styles/contemporary.webp",
      alt: "Contemporary Neapolitan-style pizza with a tall airy cornicione and restrained toppings.",
      width: 900,
      height: 900,
      fileSizeBytes: 126934,
      audit: "Retain: clearly shows a larger rim than classic Neapolitan without people or text.",
    },
    shape: "Round personal pizza",
    thickness: "Thin center with a more expressive rim",
    edge: "Often tall and airy, but not a single formal standard",
    interior: "Open structure when flour, fermentation and handling support it",
    base: "Soft center with high-heat bake behavior",
    bakingSurface: "Hot pizza oven floor",
    ovenEnvironment: "High-heat pizza oven",
    bakeStyle: "Fast bake; exact timing varies by maker and formula",
    cheeseTreatment: "Often fresh cheese with modern topping variation",
    sauceTreatment: "Usually restrained tomato base or modern topping composition",
    toppingDensity: "Variable, but still needs balance",
    eatingExperience: "Light, dramatic rim with a soft center",
    whatYouSee: ["Larger cornicione", "Modern topping choices", "Round Neapolitan family geometry", "Emphasis on dough structure"],
    whatYouFeel: ["Very airy rim", "Soft chew", "Open internal structure", "High sensitivity to handling"],
    whyItBehaves:
      "The style depends on a combination of flour strength, fermentation, dough handling, temperature and oven heat. A large rim alone does not define quality.",
    typicalBuild: ["Strong flour selection", "Careful fermentation", "Gentle opening", "Modern topping balance"],
    bestSuitedFor: ["Experienced high-heat baking", "Dough-structure experiments", "Comparing flour and fermentation choices"],
    commonConfusion:
      "Contemporary Neapolitan is not one universal formula. Not all examples are extremely high hydration, and not every puffy rim is automatically better.",
    relatedLearning: [sharedRelated.flour, sharedRelated.hydration, sharedRelated.dough, sharedRelated.ovens],
  },
  {
    id: "new-york",
    name: "New York",
    shortName: "New York",
    origin: "New York, United States",
    icon: "pizza",
    support: "learning",
    supportNote: "Learning guide",
    description: "A large round pie built for foldable slices, a crisp underside and flexible chew.",
    image: {
      src: "/pizza-styles/new-york.webp",
      alt: "Large round New York-style cheese pizza with a thin foldable slice structure and low rim.",
      width: 900,
      height: 900,
      fileSizeBytes: 135724,
      audit: "Retain: visibly low rim and broad cheese coverage distinguish it from Neapolitan.",
    },
    shape: "Large round pie",
    thickness: "Medium-thin",
    edge: "Lower rim than Neapolitan",
    interior: "Flexible chew",
    base: "Crisp underside with enough structure to fold",
    bakingSurface: "Stone, steel or deck surface",
    ovenEnvironment: "Lower heat than Neapolitan, often suitable for strong home-oven setups",
    bakeStyle: "Longer bake than Neapolitan",
    cheeseTreatment: "Low-moisture mozzarella, often shredded or sliced",
    sauceTreatment: "Cooked or seasoned tomato sauce is common",
    toppingDensity: "Moderate; slice must stay foldable",
    eatingExperience: "Foldable, chewy, crisp and slice-oriented",
    whatYouSee: ["Large round pizza", "Low edge", "Mottled cheese and sauce", "Slices made to fold"],
    whatYouFeel: ["Crisp base", "Flexible middle", "Chewy edge", "Less wet than fresh-cheese styles"],
    whyItBehaves:
      "Oil and sometimes sugar are common adaptations for a longer, lower-temperature bake. Low-moisture cheese and a sturdier base help the slice stay foldable.",
    typicalBuild: ["Seasoned tomato sauce", "Low-moisture mozzarella", "Moderate topping load", "Slice service"],
    bestSuitedFor: ["Home ovens with a steel or stone", "Large shared pies", "Foldable slices", "Lower-moisture cheese setups"],
    commonConfusion:
      "It is not simply a larger Neapolitan pizza. The dough, cheese, sauce and bake profile are adapted for a different result.",
    relatedLearning: [sharedRelated.ovens, sharedRelated.sauce, sharedRelated.toppings, sharedRelated.dough],
  },
  {
    id: "detroit",
    name: "Detroit",
    shortName: "Detroit",
    origin: "Detroit, United States",
    icon: "oven",
    support: "learning",
    supportNote: "Learning guide",
    description: "A rectangular pan pizza with an airy crumb, crisp fried base and caramelized cheese edge.",
    image: {
      src: "/pizza-styles/detroit.webp",
      alt: "Detroit-style rectangular pan pizza with sauce stripes and cheese baked to the edges.",
      width: 900,
      height: 900,
      fileSizeBytes: 179866,
      audit: "Retain: accurate rectangular pan, sauce stripes and clear style geometry; edge detail is acceptable.",
    },
    shape: "Rectangular or square pan pizza",
    thickness: "Moderately thick but airy",
    edge: "Crisp caramelized cheese edge",
    interior: "Soft, open pan crumb",
    base: "Oil-crisped and fried against the pan",
    bakingSurface: "Oiled metal pan",
    ovenEnvironment: "Home oven or deck oven with strong pan heat",
    bakeStyle: "Longer pan bake",
    cheeseTreatment: "Cheese pushed to the pan edge",
    sauceTreatment: "Sauce often added above cheese or in stripes",
    toppingDensity: "Can carry more than Neapolitan but still needs balance",
    eatingExperience: "Crisp edges, soft interior, rich cheese edge",
    whatYouSee: ["Rectangular pan", "Sauce stripes", "Cheese to the edge", "Corner pieces with crisp cheese"],
    whatYouFeel: ["Crisp fried base", "Airy interior", "Chewy edge", "Rich pan-baked bite"],
    whyItBehaves:
      "The pan, oil, cheese-to-edge placement and bake profile create the texture. Making a Neapolitan dough thicker will not reproduce the same edge or base.",
    typicalBuild: ["Pan-proofed dough", "Cheese to the edge", "Sauce above or after cheese", "Oil and pan heat as texture tools"],
    bestSuitedFor: ["Oiled metal pans", "Home ovens", "Sharing by squares", "Crispy cheese-edge lovers"],
    commonConfusion:
      "Detroit is not just Sicilian pizza with different toppings. The edge cheese, pan tradition and sauce architecture are central.",
    relatedLearning: [sharedRelated.ovens, sharedRelated.gear, sharedRelated.sauce, sharedRelated.toppings],
  },
  {
    id: "roman-tonda",
    name: "Roman Tonda",
    shortName: "Roman Tonda",
    origin: "Rome, Italy",
    icon: "pizza",
    support: "learning",
    supportNote: "Learning guide",
    description: "A round Roman pizza with a very thin, crisp base and low edge.",
    image: {
      src: "/pizza-styles/roman-thin.webp",
      alt: "Roman Tonda-style round pizza with a very thin crisp base and low edge.",
      width: 900,
      height: 900,
      fileSizeBytes: 124502,
      audit: "Retain and relabel: current asset accurately represents a low-rim thin Roman round style.",
    },
    shape: "Round",
    thickness: "Very thin",
    edge: "Low or almost flat",
    interior: "Firm and crisp rather than airy",
    base: "Distinctly crisp",
    bakingSurface: "Stone, steel or deck",
    ovenEnvironment: "Moderate to high oven heat, not Neapolitan-fast",
    bakeStyle: "Longer than Neapolitan, focused on crispness",
    cheeseTreatment: "Style-dependent",
    sauceTreatment: "Often spread closer to the edge",
    toppingDensity: "Light enough to preserve crispness",
    eatingExperience: "Thin, crisp, snappy and structurally firm",
    whatYouSee: ["Round pizza", "Low edge", "Thin profile", "More even topping coverage"],
    whatYouFeel: ["Crisp bite", "Firm slice", "Less soft rim", "Cleaner crunch"],
    whyItBehaves:
      "The thin shaping, low edge and bake profile aim for crispness rather than the soft elastic center of Neapolitan pizza.",
    typicalBuild: ["Thin round dough", "Controlled sauce", "Moderate cheese", "Toppings kept light enough for crispness"],
    bestSuitedFor: ["Crisp-pizza goals", "Home ovens with stone or steel", "People who prefer structure over softness"],
    commonConfusion:
      "Roman pizza can mean more than one thing. Roman Tonda is not the same as Roman al Taglio or Teglia.",
    relatedLearning: [sharedRelated.hydration, sharedRelated.flour, sharedRelated.ovens, sharedRelated.toppings],
  },
  {
    id: "roman-al-taglio",
    name: "Roman al Taglio / Teglia",
    shortName: "Roman al Taglio",
    origin: "Rome, Italy",
    icon: "checklist",
    support: "learning",
    supportNote: "Learning guide",
    description: "A rectangular Roman pan format, often cut by the piece, with crisp base and airy interior.",
    shape: "Rectangular pan or tray",
    thickness: "Medium to thick, variable",
    edge: "Open pan edge rather than caramelized Detroit cheese wall",
    interior: "Airy, irregular crumb when executed well",
    base: "Crisp sheet-pan base",
    bakingSurface: "Oiled or prepared pan / tray",
    ovenEnvironment: "Deck oven or strong home oven adaptation",
    bakeStyle: "Longer bake; toppings may be staged before, during or after baking",
    cheeseTreatment: "Variable by topping style",
    sauceTreatment: "Variable; often part of a broader topping system",
    toppingDensity: "Often more varied than round styles",
    eatingExperience: "Crisp base, airy interior, slice-by-weight feeling",
    whatYouSee: ["Rectangular sheet format", "Open crumb", "Crisp base", "Toppings arranged for cut portions"],
    whatYouFeel: ["Light pan structure", "Crisp bottom", "Airy middle", "Less cheese-edge richness than Detroit"],
    whyItBehaves:
      "The pan shape, dough strength, fermentation and careful handling support an airy sheet structure. It is not just Detroit without cheese edges.",
    typicalBuild: ["Strong, extensible dough", "Pan stretching", "Often staged toppings", "Cut-and-serve format"],
    bestSuitedFor: ["Sheet-pan learning", "Slice service", "Comparing crumb and base texture", "Bakers comfortable with wetter doughs"],
    commonConfusion:
      "It should not be merged with Roman Tonda or Detroit. Tonda is round and thin; Detroit depends on cheese-to-edge pan architecture.",
    relatedLearning: [sharedRelated.flour, sharedRelated.hydration, sharedRelated.ovens, sharedRelated.gear],
  },
  {
    id: "sicilian",
    name: "Sicilian / Italian-American Sicilian",
    shortName: "Sicilian",
    origin: "Sicily and Italian-American bakeries",
    icon: "pizza",
    support: "learning",
    supportNote: "Learning guide",
    description: "A term that can mean regional Sicilian traditions such as sfincione or Italian-American rectangular pan pizza.",
    image: {
      src: "/pizza-styles/sicilian.webp",
      alt: "Italian-American Sicilian-style rectangular pan pizza with a thick bread-like base and cheese-tomato top.",
      width: 900,
      height: 900,
      fileSizeBytes: 148010,
      audit: "Retain and label carefully: it reads as Italian-American Sicilian pan pizza, not all Sicilian regional forms.",
    },
    shape: "Often rectangular in Italian-American pan context; regional forms vary",
    thickness: "Thicker, bread-like pan structure",
    edge: "Pan edge, less cheese-wall focused than Detroit",
    interior: "Soft and bready to airy depending on version",
    base: "Oil-crisped pan base",
    bakingSurface: "Pan or tray",
    ovenEnvironment: "Home oven, bakery oven or deck oven depending on form",
    bakeStyle: "Longer pan bake",
    cheeseTreatment: "Regional and Italian-American versions differ",
    sauceTreatment: "Can include thicker tomato, onions, anchovies or breadcrumb traditions in sfincione",
    toppingDensity: "Variable",
    eatingExperience: "Shareable, thicker and bakery-like",
    whatYouSee: ["Rectangular pan form in many Italian-American versions", "Thicker base", "Sauce and cheese adaptations", "Regional variation"],
    whatYouFeel: ["Soft bread-like bite", "Crisp pan bottom", "More substantial slice", "Less foldable than New York"],
    whyItBehaves:
      "The term covers more than one tradition. Pan thickness, oil, topping order and regional ingredients all change the result.",
    typicalBuild: ["Regional sfincione may include onion, anchovy, caciocavallo and breadcrumbs", "Italian-American versions often use tomato and cheese on a thick rectangular base", "Pan support is central"],
    bestSuitedFor: ["Sharing", "Bakery-style squares", "Home oven pan baking", "Learning pan moisture control"],
    commonConfusion:
      "Sicilian is not one universal square cheese pizza, and Detroit is not merely Sicilian with a different topping order.",
    relatedLearning: [sharedRelated.ovens, sharedRelated.sauce, sharedRelated.toppings, sharedRelated.gear],
  },
] as const;

export const pizzaStyleComparisonFields = [
  "shape",
  "thickness",
  "edge",
  "interior",
  "base",
  "bakingSurface",
  "ovenEnvironment",
  "bakeStyle",
  "cheeseTreatment",
  "sauceTreatment",
  "toppingDensity",
  "eatingExperience",
] as const;

export const pizzaStyleGoalGuide = [
  { goal: "I want soft and fast-baked", styleId: "neapolitan" },
  { goal: "I want a more expressive airy rim", styleId: "contemporary-neapolitan" },
  { goal: "I want a foldable slice", styleId: "new-york" },
  { goal: "I want crispy cheese edges", styleId: "detroit" },
  { goal: "I want extremely thin and crisp", styleId: "roman-tonda" },
  { goal: "I want an airy pan pizza", styleId: "roman-al-taglio" },
  { goal: "I want a thick bakery-style square", styleId: "sicilian" },
] as const satisfies readonly { goal: string; styleId: PizzaStyleEducationId }[];

export function pizzaStyleEducationById(id: PizzaStyleEducationId): PizzaStyleEducation {
  return pizzaStyleEducation.find((style) => style.id === id)!;
}
