"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppSignature from "@/components/AppSignature";
import { ovens, recommendOvens, type OvenBudget, type OvenPlace, type OvenPriority } from "@/lib/ovens";

const copy = {
  fi: { back: "Laskuri", guide: "Ohjeet ja terminologia", eyebrow: "Oven Guide", title: "Oikea pizzauuni riippuu siitä, missä ja miten paistat.", intro: "Valitse ensin budjetti, käyttöpaikka ja tärkein ominaisuus. Saat kolme järkevää lähtövaihtoehtoa – sekä rehelliset syyt olla ostamatta niitä.", budget: "Kokonaisbudjetti uunille", place: "Missä paistat?", priority: "Mikä on tärkeintä?", starter: "Alle 350 €", mid: "350–700 €", premium: "Yli 700 €", indoor: "Sisällä", outdoor: "Ulkona", either: "Kumpikin käy", easy: "Helppous", portable: "Siirrettävyys", performance: "Suorituskyky", picks: "Sinulle sopivimmat lähtökohdat", compare: "Markkinoiden merkittävät vaihtoehdot", compareLead: "Hintaluokat ovat suuntaa antavia Euroopan hintoja. Tarkista aina päivän hinta, kaasuliitin ja sähkövaatimukset paikalliselta myyjältä.", good: "Hyvää", bad: "Huonoa", best: "Sopii parhaiten", avoid: "Älä valitse, jos", source: "Valmistajan tiedot", ease: "Helppous", portability: "Liikuteltavuus", power: "Teho", value: "Vastine", total: "Todellinen budjetti", totalIntro: "Pelkkä uuni ei riitä. Yhteisöissä yleisin yllätys on tarvikkeiden ja säilytyksen kustannus.", kits: [["0–180 €", "Nykyinen uuni + 6–8 mm paistoteräs + infrapunalämpömittari + tukeva lapio."], ["250–650 €", "Kaasu-uuni + ohut alumiinilapio + kääntölapio + suojapeite + kaasupullo ja paineensäädin."], ["700–1 400 €", "Tilava premium-uuni tai sähköuuni + työpöytä/jalusta + laadukkaat lapiot + säilytys + varaosa- ja huoltosuunnitelma."], ["1 500 €+", "Pysyvä ulkokeittiö: palamaton taso, sääsuoja, valaistus, työtila, kaasun turvallinen sijoitus ja mahdollinen sähkötyö."]], checklist: "Tarkista ennen ostamista", checks: ["Mahtuuko oma tavallinen pizzakokosi aukosta ja kiveen?", "Palautuuko kivi kuuden pizzan sarjassa vai joudutko odottamaan?", "Missä kuuma, likainen uuni säilytetään talvella?", "Sisältyvätkö lapio, suojus, jalusta ja lämpömittari hintaan?", "Onko laite varmasti hyväksytty sisäkäyttöön?", "Riittääkö pistorasia ja sulake sähköuunille?", "Saatko varaosia ja oikean kaasuliittimen Suomessa?"], community: "Mitä testeistä ja yhteisöistä toistuu", communityText: "Maksimilämpö ei yksin ratkaise. Käyttäjät puhuvat eniten kiven lämmön palautumisesta, suuaukon tilasta, liekin hallinnasta, puhdistuksesta ja siitä, jaksaako painavan uunin todella ottaa esiin. Kaasu voittaa helppoudessa, sähkö ympärivuotisuudessa ja suuri kupu-uuni lämmön vakaudessa.", sources: "Lähteet ja yhteisöt", note: "Mallisto ja hinnat muuttuvat. Tämä opas ei sisällä maksettuja sijoituksia tai affiliate-linkkejä." },
  en: { back: "Calculator", guide: "Guide & glossary", eyebrow: "Oven Guide", title: "The right pizza oven depends on where and how you bake.", intro: "Choose budget, location and your main priority. You will get three sensible starting points – including honest reasons not to buy them.", budget: "Total oven budget", place: "Where do you bake?", priority: "What matters most?", starter: "Under €350", mid: "€350–700", premium: "Over €700", indoor: "Indoors", outdoor: "Outdoors", either: "Either", easy: "Ease", portable: "Portability", performance: "Performance", picks: "Best starting points for you", compare: "Significant market options", compareLead: "Price bands are indicative European prices. Always check current price, gas connector and electrical requirements with a local seller.", good: "Pros", bad: "Cons", best: "Best for", avoid: "Do not choose if", source: "Manufacturer details", ease: "Ease", portability: "Portability", power: "Power", value: "Value", total: "The real budget", totalIntro: "The oven alone is not enough. Accessories and storage are a common community surprise.", kits: [["€0–180", "Current oven + 6–8 mm baking steel + infrared thermometer + solid peel."], ["€250–650", "Gas oven + thin aluminium peel + turning peel + cover + gas bottle and regulator."], ["€700–1,400", "Large premium or electric oven + table/stand + quality peels + storage + service plan."], ["€1,500+", "Permanent outdoor kitchen: fire-safe surface, weather cover, lighting, workspace, safe gas placement and possible electrical work."]], checklist: "Check before buying", checks: ["Does your normal pizza size fit through the opening and on the stone?", "Will the stone recover across six pizzas?", "Where will a hot, dirty oven live in winter?", "Are peel, cover, stand and thermometer included?", "Is the appliance explicitly approved for indoor use?", "Can the circuit and socket support an electric oven?", "Are spare parts and the correct gas connector available locally?"], community: "What reviews and communities repeat", communityText: "Maximum temperature is not enough. Users repeatedly discuss stone recovery, opening space, flame control, cleaning and whether a heavy oven will really be brought out. Gas wins on convenience, electric on year-round use, and a large dome on thermal stability.", sources: "Sources and communities", note: "Ranges and prices change. This guide contains no paid rankings or affiliate links." },
} as const;

const externalSources = [["Ooni", "https://eu.ooni.com/collections/ovens"], ["Gozney", "https://www.gozney.com/collections/ovens"], ["Effeuno", "https://www.effeuno.biz/en/"], ["Witt", "https://www.wittpizza.com/"], ["Cozze", "https://cozze-pizza.com/"], ["Serious Eats oven tests", "https://www.seriouseats.com/best-pizza-ovens-7099135"], ["PizzaMaking forum", "https://www.pizzamaking.com/forum/index.php"], ["Reddit · r/ooni", "https://www.reddit.com/r/ooni/"], ["Reddit · r/Pizza", "https://www.reddit.com/r/Pizza/"]] as const;

export default function OvensPage() {
  const [ready, setReady] = useState(false); const [budget, setBudget] = useState<OvenBudget>("mid"); const [place, setPlace] = useState<OvenPlace>("outdoor"); const [priority, setPriority] = useState<OvenPriority>("easy"); const t = copy.en;
  useEffect(() => { document.documentElement.lang = "en"; setReady(true); }, []);
  const picks = useMemo(() => recommendOvens(budget, place, priority), [budget, place, priority]); if (!ready) return <main className="min-h-screen bg-cream"/>;
  const button = (active: boolean) => `rounded-xl border px-4 py-3 text-sm font-bold transition ${active ? "border-tomato bg-tomato text-white" : "border-ink/10 bg-white text-ink/60"}`;
  return <main className="min-h-screen bg-cream px-4 py-5 text-ink sm:px-6 sm:py-8"><div className="mx-auto max-w-6xl">
    <header className="flex items-center justify-between gap-3"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-tomato text-white">🔥</span><strong>Dough<span className="text-tomato">Tools</span></strong></Link><div className="flex gap-2"><Link href="/guide" className="hidden rounded-full border border-ink/10 bg-white/70 px-4 py-2 text-xs font-bold sm:block">{t.guide}</Link><Link href="/" className="rounded-full bg-ink px-4 py-2 text-xs font-bold text-white">{t.back}</Link></div></header>
    <section className="py-10 sm:py-14"><p className="text-xs font-extrabold uppercase tracking-[.22em] text-tomato">{t.eyebrow}</p><h1 className="mt-3 max-w-4xl font-display text-4xl font-semibold leading-none sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-ink/55 sm:text-base">{t.intro}</p></section>
    <section className="rounded-[1.75rem] bg-white/80 p-5 shadow-card sm:p-7"><div className="grid gap-6 lg:grid-cols-3"><fieldset><legend className="mb-3 text-sm font-extrabold">1. {t.budget}</legend><div className="grid gap-2">{(["starter", "mid", "premium"] as OvenBudget[]).map(x => <button type="button" key={x} onClick={() => setBudget(x)} className={button(budget === x)}>{t[x]}</button>)}</div></fieldset><fieldset><legend className="mb-3 text-sm font-extrabold">2. {t.place}</legend><div className="grid gap-2">{(["indoor", "outdoor", "either"] as OvenPlace[]).map(x => <button type="button" key={x} onClick={() => setPlace(x)} className={button(place === x)}>{t[x]}</button>)}</div></fieldset><fieldset><legend className="mb-3 text-sm font-extrabold">3. {t.priority}</legend><div className="grid gap-2">{(["easy", "portable", "performance"] as OvenPriority[]).map(x => <button type="button" key={x} onClick={() => setPriority(x)} className={button(priority === x)}>{t[x]}</button>)}</div></fieldset></div><h2 className="mt-8 font-display text-3xl font-semibold">{t.picks}</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{picks.map((oven, i) => <article key={oven.id} className={`rounded-2xl p-5 ${i === 0 ? "bg-ink text-white" : "bg-leaf/[.08]"}`}><span className="text-3xl">{oven.icon}</span><p className={`mt-3 text-[10px] font-extrabold uppercase tracking-wider ${i === 0 ? "text-[#e8c98a]" : "text-leaf"}`}>#{i + 1} · {oven.price}</p><h3 className="mt-1 text-xl font-extrabold">{oven.maker} {oven.name}</h3><p className={`mt-3 text-sm leading-6 ${i === 0 ? "text-white/60" : "text-ink/55"}`}>{oven.bestEn}</p></article>)}</div></section>
    <section className="py-14"><h2 className="font-display text-4xl font-semibold">{t.compare}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-ink/50">{t.compareLead}</p><div className="mt-7 grid gap-5 md:grid-cols-2">{ovens.map(oven => { const good = oven.goodEn; const bad = oven.badEn; return <article key={oven.id} className="overflow-hidden rounded-[1.5rem] border border-white bg-white/80 shadow-card"><div className="flex items-start justify-between gap-4 border-b border-ink/10 p-5"><div><span className="text-3xl">{oven.icon}</span><h3 className="mt-2 text-xl font-extrabold">{oven.maker} {oven.name}</h3><p className="mt-1 text-xs text-ink/45">{oven.fuel} · {oven.size}</p></div><span className="rounded-full bg-tomato/10 px-3 py-1.5 text-xs font-extrabold text-tomato">{oven.price}</span></div><div className="grid grid-cols-3 border-b border-ink/10 text-center text-xs"><div className="p-3"><span className="block text-ink/35">Max</span><strong>{oven.heat}</strong></div><div className="border-x border-ink/10 p-3"><span className="block text-ink/35">Bake</span><strong>{oven.bake}</strong></div><div className="p-3"><span className="block text-ink/35">{t.value}</span><strong>{"●".repeat(oven.score.value)}{"○".repeat(5 - oven.score.value)}</strong></div></div><div className="grid gap-5 p-5 sm:grid-cols-2"><div><h4 className="text-xs font-extrabold text-leaf">+ {t.good}</h4><ul className="mt-2 space-y-2 text-xs leading-5 text-ink/55">{good.map(x => <li key={x}>• {x}</li>)}</ul></div><div><h4 className="text-xs font-extrabold text-tomato">– {t.bad}</h4><ul className="mt-2 space-y-2 text-xs leading-5 text-ink/55">{bad.map(x => <li key={x}>• {x}</li>)}</ul></div></div><div className="border-t border-ink/10 bg-ink/[.025] p-5 text-xs leading-5"><p><strong>{t.best}:</strong> {oven.bestEn}</p><p className="mt-2 text-ink/50"><strong>{t.avoid}:</strong> {oven.avoidEn}</p><a href={oven.source} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold text-tomato">{t.source} ↗</a></div></article>})}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-[1.5rem] bg-ink p-6 text-white"><h2 className="font-display text-3xl font-semibold">{t.total}</h2><p className="mt-3 text-sm leading-6 text-white/55">{t.totalIntro}</p><div className="mt-5 space-y-3">{t.kits.map(([price, body]) => <div key={price} className="rounded-xl border border-white/10 bg-white/[.05] p-4"><strong className="text-[#e8c98a]">{price}</strong><p className="mt-1 text-xs leading-5 text-white/55">{body}</p></div>)}</div></article><article className="rounded-[1.5rem] bg-leaf/[.09] p-6"><h2 className="font-display text-3xl font-semibold">{t.checklist}</h2><ul className="mt-5 space-y-3">{t.checks.map(x => <li key={x} className="flex gap-3 text-sm leading-6 text-ink/60"><span className="font-bold text-leaf">✓</span>{x}</li>)}</ul></article></section>
    <section className="mt-5 rounded-[1.5rem] border border-tomato/15 bg-tomato/[.06] p-6"><h2 className="font-display text-3xl font-semibold">{t.community}</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-ink/60">{t.communityText}</p></section>
    <Link href="/gear" className="mt-5 flex items-center justify-between rounded-[1.5rem] bg-leaf p-6 text-white shadow-card"><div><span className="text-[10px] font-extrabold uppercase tracking-wider text-white/55">Next step</span><h2 className="mt-1 font-display text-3xl font-semibold">What do you need besides the oven?</h2></div><span className="text-3xl">→</span></Link>
    <section className="py-12"><h2 className="font-display text-3xl font-semibold">{t.sources}</h2><div className="mt-4 flex flex-wrap gap-2">{externalSources.map(([label, href]) => <a key={href} href={href} target="_blank" rel="noreferrer" className="rounded-full border border-ink/10 bg-white px-4 py-2 text-xs font-bold text-ink/55">{label} ↗</a>)}</div><p className="mt-5 text-xs text-ink/40">{t.note}</p><footer className="mt-8 border-t border-ink/10 pt-6"><AppSignature /></footer></section>
  </div></main>;
}
